### Part 1 : Word Embeddings and Self attention

In [1]:
!wget http://nlp.stanford.edu/data/wordvecs/glove.6B.zip
!unzip glove.6B.zip

--2021-01-29 17:38:46--  http://nlp.stanford.edu/data/wordvecs/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/wordvecs/glove.6B.zip [following]
--2021-01-29 17:38:46--  https://nlp.stanford.edu/data/wordvecs/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/wordvecs/glove.6B.zip [following]
--2021-01-29 17:38:47--  http://downloads.cs.stanford.edu/nlp/data/wordvecs/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182753 (822M) [applic

In [2]:
import pandas as pd 
glove = pd.read_csv('glove.6B.100d.txt', sep=" ", quoting=3, header=None, index_col=0)
glove.head()

1         2        3    ...      98       99        100
0                                 ...                            
the -0.038194 -0.244870  0.72812  ... -0.14590  0.82780  0.270620
,   -0.107670  0.110530  0.59812  ... -0.83155  0.45293  0.082577
.   -0.339790  0.209410  0.46348  ... -0.23394  0.47298 -0.028803
of  -0.152900 -0.242790  0.89837  ... -0.59100  1.00390  0.206640
to  -0.189700  0.050024  0.19084  ... -0.39804  0.47647 -0.159830

[5 rows x 100 columns]

In [3]:
glove_embedding = {key: val.values for key, val in glove.T.items()}

In [16]:
print(glove_embedding['the'].shape)
glove_embedding['the'][:20]

(100,)


array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,
       -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,
        0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,
       -0.31743 , -0.48336 ])

In [14]:
import torch

river_emb = torch.tensor(glove_embedding['river'])[None,:]
bank_emb = torch.tensor(glove_embedding['bank'])[None,:]

In [13]:
river_emb.shape

torch.Size([1, 100])

In [15]:
from torch import nn

cosine = nn.CosineSimilarity()
cosine(river_emb,bank_emb)

tensor([0.3345], dtype=torch.float64)

In [42]:
string = ["bank","of","the","river"]
W1 = torch.tensor(glove_embedding[string[0]])
weights = torch.rand((4,100))
reweights_W1 = torch.rand(4)

for i in range(len(string)):
  word = torch.tensor(glove_embedding[string[i]])
  weights[i,:] = word
  reweights_W1[i]=(torch.dot(W1,word))


In [43]:
reweights_W1

tensor([46.4003, 20.8238, 21.5645, 16.5502])

In [44]:
norm_rewieghts = reweights_W1/torch.sum(reweights_W1)

In [45]:
norm_rewieghts

tensor([0.4405, 0.1977, 0.2047, 0.1571])

In [46]:
torch.sum(norm_rewieghts)

tensor(1.)

In [52]:
new_reweighted_W1_vector = norm_rewieghts@weights

In [54]:
cosine(river_emb,new_reweighted_W1_vector[None,:])

tensor([0.5966], dtype=torch.float64)

In [66]:
cosine(torch.tensor(glove_embedding['water'])[None,:],bank_emb)

tensor([0.4943], dtype=torch.float64)

In [69]:
cosine(torch.tensor(glove_embedding['water'])[None,:],new_reweighted_W1_vector[None,:])

tensor([0.5709], dtype=torch.float64)

In [70]:
cosine(torch.tensor(glove_embedding['money'])[None,:],bank_emb)

tensor([0.5718], dtype=torch.float64)

In [71]:
cosine(torch.tensor(glove_embedding['money'])[None,:],new_reweighted_W1_vector[None,:])

tensor([0.6412], dtype=torch.float64)